### ISSUE TITLE
Applicative Dynamic

### ISSUE THREAD

**Issue by nickkuk** [mitchellwrosen/reactive-banana-extras#1]
[`Discrete`](https://hackage.haskell.org/package/reactive-banana-0.4.3.2/docs/src/Reactive-Banana-Incremental.html#Discrete) had Applicative instance. In your case it will be
```haskell
instance Applicative Dynamic where
  pure x = Dynamic never (pure x)
  f <*> x = uncurry ($) <$> pair f x where
    pair :: Dynamic a -> Dynamic b -> Dynamic (a, b)
    pair (Dynamic e1 b1) (Dynamic e2 b2) = Dynamic e b where
      b = (,) <$> b1 <*> b2
      e1b2 = flip (,) <$> b2 <@> e1
      b1e2 = (,) <$> b1 <@> e2
      e = unionWith (\(p, _) (_, q) -> (p, q)) e1b2 b1e2
```
(Does it make sense to implement `(*>)`, `(<*)` and `liftA2` (for GHC-8.2.1)?)

**Comment by mitchellwrosen** [comment]
Sure, that applicative instance looks sensible. Would you mind making a PR? (Also, I wonder why `Discrete` was removed...)

By the way, this isn't a real library :) Just some untested crap I threw together. I don't plan on putting this code on hackage or anything.

**Comment by nickkuk** [comment]
Ok, I will do PR in a short time.

I understand your position and, to be honest, didn't want to use this project as a library; I just want to keep discussion around reactive-banana library, share ideas, and then use them in my (already working) commercial project.

**Comment by mitchellwrosen** [comment]
Cool, I would love to hear about some of the ideas/patterns you have used in your commercial project. I haven't built anything sizeable yet.
