### ISSUE TITLE
applyD is partial

### ISSUE THREAD

**Issue by nickkuk** [mitchellwrosen/reactive-banana-extras#2]
Maybe `applyD` should not throw [error](https://github.com/mitchellwrosen/reactive-banana-extras/blob/7c57317f50accc1fd663f771fee56c689d469571/src/Reactive/Banana/Extras.hs#L478), but "do nothing" in the case when `updates df` occurs and `ea` not occurs? That is to use `filterJust` or even [`mergeWith`](https://github.com/HeinrichApfelmus/reactive-banana/issues/158#issuecomment-333322408).

**Comment by mitchellwrosen** [comment]
Whoops! Yes, that should be `go f (This a) = f a`

**Comment by mitchellwrosen** [comment]
Err, no, not that...

**Comment by mitchellwrosen** [comment]
I think I do want `mergeWith`. First, merge the `Event (a -> b)` with the `Event a` into `Event (Either a b)`:

```haskell
mergeWith 
  (\f a -> Just (Left (f a))) 
  (\a -> Just (Right a)) 
  (\f -> Nothing) 
  (updates df) 
  ea
```

Nice find! And a good example of `mergeWith` too!

**Comment by mitchellwrosen** [comment]
This can be done with today's `reactive-banana`, too:

```haskell
data Three a b c = One a | Two b | Three c
```

Tag all `Event (a -> b)` with `One`:

```haskell
let e1 :: Event (Three (a -> b) a b)
    e1 = One <$> updates df
```

Tag all `Event a` with `Two`:

```haskell
let e2 :: Event (Three (a -> b) a b)
    e2 = Two <$> ea
```

Union them, leaving `Three`s where they intersect:

```haskell
let e3 :: Event (Three (a -> b) a b)
    e3 = unionWith (\(One f) (Two a) -> Three (f a)) e1 e2
```

Filter down to only `Three`s:

```haskell
let e4 :: Event b
    e4 = filterJust fromThree e3

let fromThree :: Three a b c -> Maybe c
    fromThree (Three x) = Just x
    fromThree _ = Nothing
```
